stages:
  - build

.in-build:
  variables:
    PACKAGE: ""
  stage: build
  tags:
    - docker-linux
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
    - cd ..

build_KTOOLS_Linux:
  image: ${CI_REGISTRY}/clearsy-public/bbatch-linux-docker/debian-cli-qt5:11.6-v1
  extends:
    - .in-build

